server {
    listen 80;

    include       /etc/nginx/mime.types;
    types {
        application/javascript mjs;
        application/wasm wasm;
    }

    # Заголовки для Stockfish/Maia (SharedArrayBuffer)
    add_header Cross-Origin-Opener-Policy "same-origin";
    add_header Cross-Origin-Embedder-Policy "require-corp";

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # ЭТОТ БЛОК НУЖЕН ОБЯЗАТЕЛЬНО:
    location /assets/ {
        root /usr/share/nginx/html;
        # Если файла нет, вернуть 404, а не index.html
        try_files $uri =404; 
        
        # Разрешаем кеширование тяжелых моделей
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    location /onnx/ {
        alias /usr/share/nginx/html/onnx/; # Используйте alias для вложенных папок
        try_files $uri =404;
        add_header Access-Control-Allow-Origin "*";
        # Повторим типы здесь для надежности
        default_type application/javascript;
    }

    # 2. Прокси для обычных API запросов
    location /api/v1 {
        proxy_pass http://backend:8080; # 'backend' — это имя сервиса в docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Прокси для WebSocket (Самое важное для шахмат)
     location /api/v1/ws {
        proxy_pass http://backend:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        # --- ДОБАВЬТЕ ЭТИ СТРОКИ ---
        proxy_buffering off;          # Отключает накопление данных (критично для WS)
        proxy_read_timeout 3600s;     # Позволяет сокету висеть открытым 1 час
        proxy_send_timeout 3600s;     # Позволяет серверу слать данные в любой момент
        proxy_cache_bypass $http_upgrade; 
        # ---------------------------
    }
}