name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. Скачиваем код (он попадает в папку раннера)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Синхронизируем код из папки раннера в папку проекта
      # Мы используем rsync, чтобы обновить только измененные файлы
      - name: Sync files to project folder
        run: |
          rsync -avz --delete --exclude='.git' ./ /home/oleksiiko/chess-frontend/

      # 3. Пересобираем контейнер, обращаясь к общему docker-compose
      - name: Rebuild Frontend Container
        run: |
          cd /home/oleksiiko
          docker compose up -d --build frontend

      # 4. Очистка
      - name: Cleanup old images
        run: docker image prune -f
